pipelines:
  ci:
    lock_behavior: unlockWhenFinished
    environment_variables:
      COMMIT_ID: Enter commit ID
    secure_variables:
      DOCKERUSER: AES:8Ff6X60DmQPio6kEyxna8g==:EdUyhmJwxfbBQ0pq5Nf2KA==
      DOCKERPASSWORD: AES:RXRtBAZNAyB3XaQLT4OJ6Q==:AX+SB8IiMDDsadHEFjtd5Q==
    group: new-group
    parameters: # list of parameters that can be configured for a pipeline
      param1: value1
    materials:
      mygit:
        git: https://github.com/MinaMaher0/GoCD_nodejs_example
    stages:
      - git-checkout:
          jobs:
            git-checkout:
              tasks:
              - exec:
                  command: sh 
                  arguments:
                    - -c 
                    - git checkout $
              - exec:
                  command: ls
      - build-docker-image:
          jobs:
            build-image:
              tasks:
              - exec:
                  command: docker
                  arguments:
                    - build
                    - -t
                    - node-app
                    - . 
      - tag-image:
          jobs:
            tag-image:
              tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - docker tag node-app $DOCKERUSER/node-app
      - login-docker-hub:
          jobs:
            login:
              tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - docker login -u $DOCKERUSER -p $DOCKERPASSWORD 
      - push-image-to-docker-hub:
          jobs:
            pushing:
              tasks:
              - exec:
                  command: sh
                  arguments:
                    - -c
                    - docker push $DOCKERUSER/node-app       
              

