pipelines:
  ci:
    group: hhhh
    # parameters:
    #   commitID: value1
    materials:
      mygit:
        git: https://github.com/MinaMaher0/GoCD_nodejs_example
    stages:
      - print-param:
          jobs:
            print:
              tasks:
              - exec:
                  command: echo
                  arguments: 
                    - ${commitID}

