pipelines:
  ci:
    secure_variables:
      USER: "AES:8Ff6X60DmQPio6kEyxna8g==:EdUyhmJwxfbBQ0pq5Nf2KA=="
    group: new-group
    # parameters:
    #   commitID: value1
    materials:
      mygit:
        git: https://github.com/MinaMaher0/GoCD_nodejs_example
    stages:
      - build-docker-image:
          jobs:
            # build-image:
            #   tasks:
            #   - exec:
            #       command: docker
            #       arguments:
            #         - build
            #         - -t
            #         - node-app
            #         - . 
            pull-image:
              tasks:
              - exec:
                  command: docker
                  arguments:
                    - pull 
                    - $USER/jenkins-ansible
            echo:
              tasks:
              - exec:
                 command: echo
                 arguments:
                   - $USER
      
      # - push-image-to-dockerhub:
      #     jobs:
      #       print:
      #         tag-image:
      #         - exec:
      #             command: docker
      #             arguments:
      #               - tag
      #               - -t
      #               - node-app
      #               - . 
      
              

