pipelines:
  ci:
    group: new-group
    # parameters:
    #   commitID: value1
    materials:
      mygit:
        git: https://github.com/MinaMaher0/GoCD_nodejs_example
    stages:
      - build-docker-image:
          jobs:
            build-image:
              tasks:
              - exec:
                  command: docker
                  arguments:
                    - build
                    - -t
                    - node-app
                    - . 
      # - push-image-to-dockerhub:
      #     jobs:
      #       print:
      #         tag-image:
      #         - exec:
      #             command: docker
      #             arguments:
      #               - tag
      #               - -t
      #               - node-app
      #               - . 
      
              

